---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gotk-system
  namespace: gotk-system
spec:
  interval: 10m0s
  path: ./local-k8s-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-system

