apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gotk-apps
  namespace: gotk-system
spec:
  dependsOn:
    - name: gotk-system
  serviceAccount:
    name: gotk-apps-reconciler
    namespace: gotk-apps 
  interval: 5m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-apps
