apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gotk-apps-reconciler
  namespace: gotk-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gotk-apps-reconciler
subjects:
- kind: ServiceAccount
  name: gotk-apps-reconciler
  namespace: gotk-apps
